# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanJi',
            fields=[
                ('bId', models.AutoField(primary_key=True, serialize=False)),
                ('bName', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sId', models.AutoField(primary_key=True, serialize=False)),
                ('sName', models.CharField(max_length=32)),
                ('sAge', models.CharField(max_length=6)),
                ('sGender', models.CharField(max_length=6)),
                ('sPhone', models.CharField(max_length=32)),
                ('joinDate', models.DateField(verbose_name='入学时间')),
                ('banJi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BanJi')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tId', models.AutoField(primary_key=True, serialize=False)),
                ('tName', models.CharField(max_length=32)),
                ('tAge', models.CharField(max_length=6)),
                ('tGender', models.CharField(max_length=6)),
                ('tPhone', models.CharField(max_length=32)),
                ('salary', models.CharField(max_length=32)),
                ('userName', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('uId', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher2user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserType', to_field='role'),
        ),
        migrations.AddField(
            model_name='banji',
            name='banji2teacher',
            field=models.ManyToManyField(to='app.Teacher'),
        ),
    ]
